apiVersion: v1
kind: ConfigMap
metadata:
 name: mongodb-conf
 namespace: m-ecommerce
data:
 host: mongodb-service
 port: "27017"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: m-ecommerce
spec:
  selector:
    matchLabels:
      app: order-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: order-deployment
    spec:
      containers:
        - name: order-deployment
          image: asmaeel/order-microservice:1.0
          ports:
            - containerPort: 5002
              name: order-port
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-conf
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongodb-conf
                  key: port
            - name: MONGO_URI
              value: "mongodb://mongodb-service/microservices"
