apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: m-ecommerce
  labels:
    app: order-service
spec:
  selector:
    app: order-deployment
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002